"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from libs.VERSION import VERSION

APP = ["SwitchHosts.py"]
DATA_FILES = ["img/logo.png"]

setup(
    app=APP,
    data_files=DATA_FILES,
    options={
        "py2app": {
            "argv_emulation": False,
            "includes": ["wx"],
            "iconfile": "img/logo.icns",
            "resources": [],
            "plist": {
                "CFBundleName": "SwitchHosts!",
                "CFBundleShortVersionString": VERSION,  # must be in X.X.X format
                "CFBundleGetInfoString": "SwitchHosts! %s" % VERSION,
                "CFBundleExecutable": "SwitchHosts!",
                "CFBundleIdentifier": "net.oldj.switchhosts",
                },
            },
        },
    setup_requires=["py2app"],
)

